---
title: 'Parole Inmate: Data Dictionary'
author: "Saeid Abolfazli"
date: "May 9, 2016"
output: pdf_document
---
This dataset is related to United States 2004 National Corrections Reporting Program, a nationwide census of parole releases that occurred during 2004. We limited our focus to parolees who served no more than 6 months in prison and whose maximum sentence for all charges did not exceed 18 months. The dataset contains all such parolees who either successfully completed their term of parole during 2004 or those who violated the terms of their parole during that year. The dataset contains the following variables:

* **male:** 1 if the parolee is male, 0 if female
* **race:** 1 if the parolee is white, 2 otherwise
* **age:** the parolee's age (in years) when he or she was released from prison
* **state:** a code for the parolee's state. 2 is Kentucky, 3 is Louisiana, 4 is Virginia, and 1 is any other state. The three states were selected due to having a high representation in the dataset.
* **time.served:** the number of months the parolee served in prison (limited by the inclusion criteria to not exceed 6 months).
* **max.sentence:** the maximum sentence length for all charges, in months (limited by the inclusion criteria to not exceed 18 months).
* **multiple.offenses:** 1 if the parolee was incarcerated for multiple offenses, 0 otherwise.
* **crime:** a code for the parolee's main crime leading to incarceration. 2 is larceny, 3 is drug-related crime, 4 is driving-related crime, and 1 is any other crime.
* **violator:** 1 if the parolee violated the parole, and 0 if the parolee completed the parole without violation.

```{r}
parole <- read.table("data/parole.csv",sep=",", header=TRUE)
str(parole)
table(parole$violator)
```